const data = [
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'Technology1.jpg',
        category: 'Ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
]

export default data;