const data = [
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {

    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'technology',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'culture',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
    {
        image: 'technology1.jpg',
        category: 'ideas',
        fullname: 'Michael Chang',
        jobTitle: 'Tech Innovator',
        readingTime: '10 min',
        date: '2023-05-20',
        title: 'Emerging Technologies in 2023',
        description: 'A glimpse into the latest technological advancements and their potential impact on various industries.',
    },
]
